### PR TITLE
ベースいろいろ

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-server/1)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[dashboard.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfgeQM9m2-hayvkrM:-KMIfgeQM9m2-hayvkrN:480561426) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L2)):_

> ``` JavaScript
> var express = require("express");
> var io = require("socket.io");
> ```

こっちは ES6 にしないです？

---

_[dashboard.js, line 25 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfotPNGlt1d0hZ-zc:-KMIfotQH_blvgkPlap0:-1852370703) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L25)):_

> ``` JavaScript
> 
>   io.on('connection', (socket) => {
>     console.log("a user connected.");
> ```

log は出す方針で良いですか？

---

_[dashboard.js, line 26 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfvAp3ELiXlUF9SjF:-KMIfvAp3ELiXlUF9SjG:-92266145) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L26)):_

> ``` JavaScript
>   io.on('connection', (socket) => {
>     console.log("a user connected.");
>     socket.on("gameState", (gameState) => {
> ```

パラメータが一つときのアローファンクションにはカッコをつけなくて良いかと思います。

---

_[dashboard.js, line 27 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIg6tZf8iNGqB-1cT5:-KMIg6tZf8iNGqB-1cT6:198219104) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L27)):_

> ``` JavaScript
>     console.log("a user connected.");
>     socket.on("gameState", (gameState) => {
>       if (/active|inactive/.test(gameState.gameState)) {
> ```

gameState.gameState はなんか不思議な感じですね。他の名前は付けられないかしら。

---

_[dashboard/main.js, line 6 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIgY694twjQNhSztih:-KMIgY6A8OkMYe06naL1:-1954142491) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard/main.js#L6)):_

> ``` JavaScript
>   var gameState = "inactive";
>   var gameStateButton = document.getElementById("game-state-button");
>   gameStateButton.addEventListener("click", function() {
> ```

アローファンクションと普通の function が混じっているようなので、どちらかに統一したいですね。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[dashboard.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfgeQM9m2-hayvkrM:-KMJBTy9z-vHssLsr5b5:761711222) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L2)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> こっちは ES6 にしないです？
> </details>
> こんばんは。レビューありがとうございます。

したいのですが、node.js では（harmonyオプションつけても）動きません。

代わりに、babel-node というものを使うとできますがどうでしょう。

https://babeljs.io/docs/usage/cli/
http://qiita.com/RyotaSugawara/items/af51321b4796d671bc01

次のPRのほうがいいでしょうか。

---

_[dashboard.js, line 25 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfotPNGlt1d0hZ-zc:-KMJBpuXYzqsSbVsNMZ8:521829404) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L25)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> log は出す方針で良いですか？
> </details>
> そうですね。dashboardが接続した、みたいなのはほしいような感じです。
> それか、dashboardとか、別のところに出力したほうがいいでしょうか。

あと、ここでは `a user connected` となっていますが、#2 のPRのほうで、 `a dashboard connected` に直してあります。

---

_[dashboard.js, line 26 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfvAp3ELiXlUF9SjF:-KMJCMSfbPZehvGTLMNx:1550978497) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L26)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> パラメータが一つときのアローファンクションにはカッコをつけなくて良いかと思います。
> </details>
> ありがとうございます。直します！

---

_[dashboard.js, line 27 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIg6tZf8iNGqB-1cT5:-KMJCanzIssWva9o3A_K:1394837415) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L27)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> gameState.gameState はなんか不思議な感じですね。他の名前は付けられないかしら。
> </details>
> 引数のほうを data という名前にしてみます。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[dashboard/main.js, line 6 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIgY694twjQNhSztih:-KMJCqKUUKNecBfcPs9D:-1266098110) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard/main.js#L6)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> アローファンクションと普通の function が混じっているようなので、どちらかに統一したいですね。
> </details>
> わかりました！アローファンクションのほうに揃えます。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Comment by dadaa** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[dashboard.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfgeQM9m2-hayvkrM:-KMJGZwPRCsy1X1_1KOc:-1480683206) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L2)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> こんばんは。レビューありがとうございます。
> 
> したいのですが、node.js では（harmonyオプションつけても）動きません。
> 
> 代わりに、babel-node というものを使うとできますがどうでしょう。
> 
> https://babeljs.io/docs/usage/cli/
> http://qiita.com/RyotaSugawara/items/af51321b4796d671bc01
> 
> 次のPRのほうがいいでしょうか。
> </details>
> そうですね、やるのであれば、おっしゃる通り別の PR の方が良いと思いますー

---

_[dashboard.js, line 27 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIg6tZf8iNGqB-1cT5:-KMJG5ey4_2ao2OEVUIN:-253400040) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L27)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> 引数のほうを data という名前にしてみます。
> </details>
> この data オブジェクトは他にどんな情報を持っています？
> 適した名前があれば、そうしたいですねー

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[dashboard.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIfgeQM9m2-hayvkrM:-KMJHcqQx4838KVd7HO1:664534256) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L2)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> そうですね、やるのであれば、おっしゃる通り別の PR の方が良いと思いますー
> </details>
> わかりました。次のPRにてやります！！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[dashboard.js, line 27 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/1#-KMIg6tZf8iNGqB-1cT5:-KMJIEz03UFeJJgzQACB:1761707604) ([raw file](https://github.com/comozilla/onigo-server/blob/8671c7522afb58698ab3bbb0d21e15e642f6be80/dashboard.js#L27)):_

> この data オブジェクトは他にどんな情報を持っています？
> gameState のみです。

それで、Socket.io で、Objectでなく、そのまま文字列を送れるか試したところ、
送れたので、引数をgameStateに戻し、そこに直でgameStateを入れました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Comment by dadaa** [comment]
Reviewed 5 of 8 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/1)_

**Pull request merged**
