### PR TITLE
Manage connect

### PR DESCRIPTION
**Pull request by shundroid**
#6 と並列に作りました。

どのclientがどのorbにlinkするかを、dashboard側から設定できるようにしました。

すみませんが、レビューをよろしくお願いします。

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-server/8)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_[dashboard/js/link.js, line 42 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMTtkLb_M_X2nrk952j:-KMTtkLchUfAlbXGewB8:-1377268809) ([raw file](https://github.com/comozilla/onigo-server/blob/0607c0387cfad66115de736448ed9ebb112de0ff/dashboard/js/link.js#L42)):_

> ``` JavaScript
> function updateOrbSelect() {
>   this.orbSelectElement.innerHTML = "";
>   let editedOrbs = this.orbs.slice();
> ```

const で良いかと

---

_[dashboard/js/linkManager.js, line 40 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMTtsqtsjzlM5JwiRsR:-KMTtsquKjjCg0EmscSj:-882739934) ([raw file](https://github.com/comozilla/onigo-server/blob/0607c0387cfad66115de736448ed9ebb112de0ff/dashboard/js/linkManager.js#L40)):_

> ``` JavaScript
>   }
>   removeLink(clientKey) {
>     let keyIndex = this.linkInstances.map(instance => instance.clientKey).indexOf(clientKey);
> ```

ここも const の方が良さそうです

---

_[dashboard/js/socketManager.js, line 54 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMTu7jWaksNexXS5GW_:-KMTu7jWaksNexXS5GWa:-748685760) ([raw file](https://github.com/comozilla/onigo-server/blob/0607c0387cfad66115de736448ed9ebb112de0ff/dashboard/js/socketManager.js#L54)):_

> ``` JavaScript
>     eventPublisher.removeListener(eventName, this[methodName].bind(this));
>   }
>   let emitArgs = args;
> ```

この変数無くても良さそう

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by shundroid** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_[dashboard/js/link.js, line 42 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMTtkLb_M_X2nrk952j:-KMYzvwdRZ7XgavSTnHy:832834654) ([raw file](https://github.com/comozilla/onigo-server/blob/0607c0387cfad66115de736448ed9ebb112de0ff/dashboard/js/link.js#L42)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> const で良いかと
> </details>
> そうします。

---

_[dashboard/js/socketManager.js, line 54 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMTu7jWaksNexXS5GW_:-KMZ-1mMnkbuzEWLkldL:1828595076) ([raw file](https://github.com/comozilla/onigo-server/blob/0607c0387cfad66115de736448ed9ebb112de0ff/dashboard/js/socketManager.js#L54)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> この変数無くても良さそう
> </details>
> あ、この下の行の部分を間違えていました。args -> emitArgs です。
> その場合でも、unshift ではなく、配列を結合する方法を使用すれば、変数が消せそうなので、それで消します。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by shundroid** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_[dashboard/js/linkManager.js, line 40 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMTtsqtsjzlM5JwiRsR:-KMZ0dI9AmS6gpAHsqL6:832887645) ([raw file](https://github.com/comozilla/onigo-server/blob/0607c0387cfad66115de736448ed9ebb112de0ff/dashboard/js/linkManager.js#L40)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここも const の方が良さそうです
> </details>
> そうします！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by dadaa** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[main.js, line 34 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMdSq3mSQhfY_xpsEGY:-KMdSq3nfSyNrOY7Hl-H:-1551017935) ([raw file](https://github.com/comozilla/onigo-server/blob/d68bbc222eb61d8fb79cd22e8690a4935f0400b8/main.js#L34)):_

> ``` JavaScript
>     hp: 100
>   };
>   clients[key].commandRunner.on("command", function(commandName, args) {
> ```

アローファンクションで統一しておきましょう

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by shundroid** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[main.js, line 34 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMdSq3mSQhfY_xpsEGY:-KMiCVkw9UiUa29qAOV9:513611454) ([raw file](https://github.com/comozilla/onigo-server/blob/d68bbc222eb61d8fb79cd22e8690a4935f0400b8/main.js#L34)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> アローファンクションで統一しておきましょう
> </details>
> 統一しました！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by dadaa** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_[dashboard.js, line 61 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMlH7xxI2C8FL0A6e7Y:-KMlH7xxI2C8FL0A6e7Z:1149072365) ([raw file](https://github.com/comozilla/onigo-server/blob/06f72acd6b23c1986dafb616cd1494063b8c27c4/dashboard.js#L61)):_

> ``` JavaScript
> 
> Dashboard.prototype.addClient = function(key) {
>   this.links[key] = null;
> ```

他で this.links[key] をチェックする箇所も見受けられないので、これは意味がないんじゃないですかしら？

---

_[dashboard.js, line 69 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMlGUkCEjvOk9BUGBvO:-KMlGUkCEjvOk9BUGBvP:378974784) ([raw file](https://github.com/comozilla/onigo-server/blob/06f72acd6b23c1986dafb616cd1494063b8c27c4/dashboard.js#L69)):_

> ``` JavaScript
> Dashboard.prototype.removeClient = function(key) {
>   delete this.links[key];
>   this.sockets.forEach(socket => {
> ```

ここの emit は、delete this.links[key]; が本当できた場合にのみ発生させた方が良いかもですね。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by shundroid** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_[dashboard.js, line 61 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMlH7xxI2C8FL0A6e7Y:-KMlIHFTxDy2qj6r0UH0:2065460659) ([raw file](https://github.com/comozilla/onigo-server/blob/06f72acd6b23c1986dafb616cd1494063b8c27c4/dashboard.js#L61)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 他で this.links[key] をチェックする箇所も見受けられないので、これは意味がないんじゃないですかしら？
> </details>
> このnullというのは、clientがどのorbにも紐づいていない、というのを表しています。
> こちら側ではチェックする箇所はありませんが、dashboardのブラウザ側、
> dashboard/js/link.js で、nullのときは紐づいていない値を表示する、という風に使用するようにしました。
> ↑使用していなかったので、今使用するようにしました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by shundroid** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_[dashboard.js, line 69 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMlGUkCEjvOk9BUGBvO:-KMlLMZk7NdQcVF8svgc:-172380418) ([raw file](https://github.com/comozilla/onigo-server/blob/06f72acd6b23c1986dafb616cd1494063b8c27c4/dashboard.js#L69)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここの emit は、delete this.links[key]; が本当できた場合にのみ発生させた方が良いかもですね。
> </details>
> わかりました。そうします。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by dadaa** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[dashboard.js, line 69 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMlGUkCEjvOk9BUGBvO:-KMlMIjuREndxiS8lY_T:-1173063095) ([raw file](https://github.com/comozilla/onigo-server/blob/06f72acd6b23c1986dafb616cd1494063b8c27c4/dashboard.js#L69)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> わかりました。そうします。
> </details>
> あ、いや、伝えかた悪かったも。
> このメソッドが呼ばれ typeof this.links[key] !== "undefined" だったら delete して、emit したらいかがでしょか。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by shundroid** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[dashboard.js, line 69 [r3]](https://reviewable.io:443/reviews/comozilla/onigo-server/8#-KMlGUkCEjvOk9BUGBvO:-KMlNTPxR8ydc5A7Cu1N:1732025487) ([raw file](https://github.com/comozilla/onigo-server/blob/06f72acd6b23c1986dafb616cd1494063b8c27c4/dashboard.js#L69)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> あ、いや、伝えかた悪かったも。
> このメソッドが呼ばれ typeof this.links[key] !== "undefined" だったら delete して、emit したらいかがでしょか。
> </details>
> すみません。そうします！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Comment by dadaa** [comment]
Reviewed 12 of 17 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/8)_

**Pull request merged**
