### PR TITLE
fixed #31 Scoreboard

### LINKED ISSUE #31: スコアボートを作る
プロジェクタで全員に表示するようなスコアボード的な画面を作る
- 現在のランキング
- タイマー

### PR DESCRIPTION
**Pull request by Babibubebon**
Scoreboardをとりあえず作っておきました。

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-server/39)

### CODE REVIEW

**Comment by shundroid** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[scoreboard.js, line 11 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvl3dfAkphhveHE6Oe:-KNvl3dfAkphhveHE6Of:311732467) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard.js#L11)):_

> ``` JavaScript
> 
> function Scoreboard(port) {
>   EventEmitter.call(this);
> ```

これは必要でしょうか。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by shundroid** [comment]
Reviewed 1 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[scoreboard/js/main.js, line 6 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvltu_WpUrOVnOIEEw:-KNvltu_WpUrOVnOIEEx:202425632) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard/js/main.js#L6)):_

> ``` JavaScript
> const interval = 2000;
> 
> var Ranking = function () {
> ```

下の Orb とこれは、const でいけそうです。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by shundroid** [comment]
Reviewed 2 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

_[scoreboard/js/main.js, line 10 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvmB2czz4-h1SbDBF0:-KNvmB2dau0LbVONgKwI:-1068292584) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard/js/main.js#L10)):_

> ``` JavaScript
>   self.orbs = ko.observableArray([]);
> 
>   self.setOrbs = function (orbs) {
> ```

Webpack のとき、babel-loader を使用しているので、es6 で書くことができます。
そうすると、この行は

```
this.setOrbs = orbs => {
```

と書けそうです。

そうすると、self はいらなくなるでしょうか。

---

_[scoreboard/js/main.js, line 20 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvmSVIV5iVJ_c9HOAQ:-KNvmSVIV5iVJ_c9HOAR:1610808007) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard/js/main.js#L20)):_

> ``` JavaScript
> 
> var Orb = function (obj) {
>   const self = this;
> ```

knockout.js はよくわからないのですが、これって self を作る必要はありますでしょうか。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by shundroid** [comment]
Reviewed 2 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by Babibubebon** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

_[scoreboard.js, line 11 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvl3dfAkphhveHE6Oe:-KNvvTARPz7rsygT32dD:1007606857) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard.js#L11)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> これは必要でしょうか。
> </details>
> すみません、コピペのままでした。消しました。

---

_[scoreboard/js/main.js, line 6 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvltu_WpUrOVnOIEEw:-KNvvpxARAuIgDIhumnu:1307676724) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard/js/main.js#L6)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> 下の Orb とこれは、const でいけそうです。
> </details>
> 了解です

---

_[scoreboard/js/main.js, line 10 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvmB2czz4-h1SbDBF0:-KNvvwKpUj0s9RmJQBJk:-1392370477) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard/js/main.js#L10)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> Webpack のとき、babel-loader を使用しているので、es6 で書くことができます。
> そうすると、この行は
> 
> ```
> this.setOrbs = orbs => {
> ```
> 
> と書けそうです。
> 
> そうすると、self はいらなくなるでしょうか。
> </details>
> 書き直しましたー

---

_[scoreboard/js/main.js, line 20 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvmSVIV5iVJ_c9HOAQ:-KNvw0qy-0y9k-zx1RwZ:2078419784) ([raw file](https://github.com/comozilla/onigo-server/blob/ec601aa72c2390833655dd0a8b55219a18776c02/scoreboard/js/main.js#L20)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> knockout.js はよくわからないのですが、これって self を作る必要はありますでしょうか。
> </details>
> ただの悪しき慣習です。。。直しました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by dadaa** [comment]
Review status: 6 of 8 files reviewed at latest revision, 12 unresolved discussions.

---

_[scoreboard.js, line 28 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvvtid9f45oQxHhXED:-KNvvtid9f45oQxHhXEE:1332634046) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard.js#L28)):_

> ``` JavaScript
>   this.io.on("connection", socket => {
>     console.log("a scoreboard connected.");
> 
> ```

不思議な whitespace 発見！

---

_[scoreboard.js, line 29 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvw1x5eaL52gOEyV60:-KNvw1x5eaL52gOEyV61:30848774) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard.js#L29)):_

> ``` JavaScript
>     console.log("a scoreboard connected.");
> 
>     socket.on("request", function () {
> ```

ここもアロー関数で良さそうです

---

_[scoreboard/css/style.css, line 22 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvwMFwRXcrNbs7oGtd:-KNvwMFxU8zR_Jbn98kN:1650796314) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/css/style.css#L22)):_

> ``` CSS
> }
> 
> table td, table tr, table th {
> ```

これらは常に table の下にあるので、td, tr, th {} で良いかと思います。table 指定まであると、ちょっとだけ処理が遅くなります。
以下も同様です。

---

_[scoreboard/js/main.js, line 22 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvx1Oe3UhaPMSw-Lq9:-KNvx1Oe3UhaPMSw-LqA:-1687860606) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L22)):_

> ``` JavaScript
>   this.hp = ko.observable(obj.hp);
>   this.isTie = ko.observable(obj.isTie);
> 
> ```

スペースが入っちゃって見えるのは reviewable のバグ？

---

_[scoreboard/js/main.js, line 31 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvx97nudfaErVDlkho:-KNvx97nudfaErVDlkhp:172589795) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L31)):_

> ``` JavaScript
>   const ranking = new Ranking();
>   ko.applyBindings(ranking);
> 
> ```

ここと

---

_[scoreboard/js/main.js, line 37 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvxBCjfz2uHdJLtben:-KNvxBCjfz2uHdJLtbeo:172589795) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L37)):_

> ``` JavaScript
>     ranking.setOrbs(data.ranking);
>   });
> 
> ```

ここと

---

_[scoreboard/js/main.js, line 40 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvxCWNbSsTAcyYhi8I:-KNvxCWNbSsTAcyYhi8J:172589795) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L40)):_

> ``` JavaScript
>   socket.on("connect", () => {
>     console.log("connected");
> 
> ```

ここと

---

_[scoreboard/js/main.js, line 43 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvxDaUkGth6EhFBD8T:-KNvxDaUkGth6EhFBD8U:172589821) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L43)):_

> ``` JavaScript
>     if (intervalID)
>       clearInterval(intervalID);
> 
> ```

ここも

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by Babibubebon** [comment]
Review status: 5 of 8 files reviewed at latest revision, 12 unresolved discussions.

---

_[scoreboard.js, line 28 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvvtid9f45oQxHhXED:-KNwF0kuGgAjxTkwW66N:1976990428) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard.js#L28)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 不思議な whitespace 発見！
> </details>
> お？何か見えますか…？

---

_[scoreboard.js, line 29 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvw1x5eaL52gOEyV60:-KNwD6FTxFZbkpP_4HAX:-2121851004) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard.js#L29)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここもアロー関数で良さそうです
> </details>
> 承知です！

---

_[scoreboard/css/style.css, line 22 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvwMFwRXcrNbs7oGtd:-KNwDKNKqDnAt809CbDr:1461018992) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/css/style.css#L22)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> これらは常に table の下にあるので、td, tr, th {} で良いかと思います。table 指定まであると、ちょっとだけ処理が遅くなります。
> 以下も同様です。
> </details>
> なるほど！修正しました！

---

_[scoreboard/js/main.js, line 22 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvx1Oe3UhaPMSw-Lq9:-KNwFwlja4NKOCs649vv:1054928130) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L22)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> スペースが入っちゃって見えるのは reviewable のバグ？
> </details>
> あらら？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by dadaa** [comment]
Review status: 5 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

_[scoreboard.js, line 28 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvvtid9f45oQxHhXED:-KNwSLa0JeSXAtSSUGSk:1053428721) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard.js#L28)):_
<details><summary>

<i>Previously, Babibubebon (Babibubebon) wrote…</i></summary>



> お？何か見えますか…？
> </details>
> この行に半角スペースが４つ入ってるように見えるのよー
> もしかしたら reviewable のバグかもなので、そちらで確認してもらって無ければ教えてくださいませー

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by Babibubebon** [comment]
Review status: 5 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

_[scoreboard.js, line 28 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvvtid9f45oQxHhXED:-KNwW8NydS44JvVZC15n:-411480142) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard.js#L28)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> この行に半角スペースが４つ入ってるように見えるのよー
> もしかしたら reviewable のバグかもなので、そちらで確認してもらって無ければ教えてくださいませー
> </details>
> あ、空行はインデントしない系ということですね。把握です！Reviewableは悪くなかった！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by dadaa** [comment]
Review status: 5 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

_[scoreboard/js/main.js, line 31 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvx97nudfaErVDlkho:-KNwXY-kvpbuOaNIaYlw:160395992) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L31)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここと
> </details>
> OKす

---

_[scoreboard/js/main.js, line 37 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvxBCjfz2uHdJLtben:-KNwXQMv_Acvwn6jxGLA:160395992) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L37)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここと
> </details>
> OKす

---

_[scoreboard/js/main.js, line 40 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvxCWNbSsTAcyYhi8I:-KNwXVNqmMt5-4E_6wud:160395992) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L40)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここと
> </details>
> OKす

---

_[scoreboard/js/main.js, line 43 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-KNvxDaUkGth6EhFBD8T:-KNwXWOnGS7p9Ooyc4JO:160395992) ([raw file](https://github.com/comozilla/onigo-server/blob/19d4c9e61211f61ac78705498430ccee08025ce1/scoreboard/js/main.js#L43)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここも
> </details>
> OKす

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by shundroid** [comment]
Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39)_

**Comment by shundroid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/39#-:-KNz60Vg7fnWDTbjYgik:1417088721)_

**Pull request merged**
