### PR TITLE
Commands

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-server/6)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[commandRunner.js, line 21 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/6#-KMTnjQd0ZEwRPoVxBhb:-KMTnjQd0ZEwRPoVxBhc:-712564845) ([raw file](https://github.com/comozilla/onigo-server/blob/f9e32a33100d355b850ce3862ccace8aa5ab5f93/commandRunner.js#L21)):_

> ``` JavaScript
>         this.timeoutId = setTimeout(rotateFunction, 500);
>       };
>       rotateFunction();
> ```

こんな感じでも書けるかな。

`(rotateFunction = () => {`
`...`
`})();`

---

_[main.js, line 53 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/6#-KMTnL9eh8XmxfAvUms_:-KMTnL9eh8XmxfAvUmsa:1542311174) ([raw file](https://github.com/comozilla/onigo-server/blob/f9e32a33100d355b850ce3862ccace8aa5ab5f93/main.js#L53)):_

> ``` JavaScript
>   client.on("arriveCustomMessage", (name, data, mesID) => {
>     if (name === "commands") {
>       if (typeof data.type === "string" && data.type === "built-in") {
> ```

ここの typeof の検査は要るかしら？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/6)_

**Comment by shundroid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[main.js, line 53 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/6#-KMTnL9eh8XmxfAvUms_:-KMToDzKHmymhkq9PPM9:-1847338177) ([raw file](https://github.com/comozilla/onigo-server/blob/f9e32a33100d355b850ce3862ccace8aa5ab5f93/main.js#L53)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここの typeof の検査は要るかしら？
> </details>
> ここでは、data.type が存在するかどうかを確認しています。
> そのまま、data.type === "built-in" として、
> data.type がないとき（←built-inでないとき）、Reference Error が出たので追加しました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/6)_

**Comment by shundroid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[commandRunner.js, line 21 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/6#-KMTnjQd0ZEwRPoVxBhb:-KMTojCRcIfHYhRJ8Vkc:832887645) ([raw file](https://github.com/comozilla/onigo-server/blob/f9e32a33100d355b850ce3862ccace8aa5ab5f93/commandRunner.js#L21)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> こんな感じでも書けるかな。
> 
> `(rotateFunction = () => {`
> `...`
> `})();`
> </details>
> そうします！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/6)_

**Comment by dadaa** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/6)_

**Comment by shundroid** [comment]
ありがとうございました！

**Pull request merged**
