### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-server/5)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[dashboard.js, line 16 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/5#-KMJMukJKah0sCHdNmPc:-KMJMukLeSzy4hssHS9E:-1237690331) ([raw file](https://github.com/comozilla/onigo-server/blob/08e2c7b892c17ffbf19776b7ab79296b618492c0/dashboard.js#L16)):_

> ``` JavaScript
> 
>   var app = require('express')();
>   var server = require('http').Server(app);
> ```

この下の行も含め、ダブルコーテーションで統一していきましょう

---

_[dashboard.js, line 36 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/5#-KMJLpz4DYZTn4fGDxmL:-KMJLpz5HP_75CQk3oou:-1442645319) ([raw file](https://github.com/comozilla/onigo-server/blob/08e2c7b892c17ffbf19776b7ab79296b618492c0/dashboard.js#L36)):_

> ``` JavaScript
>       }
>     });
>     socket.on("availableCommandsCount", (data) => {
> ```

ここもカッコを取り除きましょうか。
それと、data 以外のステキな名前を是非！ :-)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/5)_

**Comment by shundroid** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[dashboard.js, line 16 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/5#-KMJMukJKah0sCHdNmPc:-KMJNEDog2Ea4-e40PNl:1263867722) ([raw file](https://github.com/comozilla/onigo-server/blob/08e2c7b892c17ffbf19776b7ab79296b618492c0/dashboard.js#L16)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> この下の行も含め、ダブルコーテーションで統一していきましょう
> </details>
> ほんとだ・・！直します

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/5)_

**Comment by shundroid** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[dashboard.js, line 36 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/5#-KMJLpz4DYZTn4fGDxmL:-KMJNXmQdVHZgI71Exfl:-981290321) ([raw file](https://github.com/comozilla/onigo-server/blob/08e2c7b892c17ffbf19776b7ab79296b618492c0/dashboard.js#L36)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここもカッコを取り除きましょうか。
> それと、data 以外のステキな名前を是非！ :-)
> </details>
> これも、gameStateと同じようにして、count とします！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/5)_

**Comment by dadaa** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/5)_

**Pull request merged**
