### PR TITLE
Ranking

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-server/30)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[rankingMaker.js, line 18 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/30#-KNLNkEj0qRLgm3CbScD:-KNLNkEkwZjbpUq2xyu7:-495174261) ([raw file](https://github.com/comozilla/onigo-server/blob/50d8d983b26842ccc4a5a3d44f78c2db7b92f162/rankingMaker.js#L18)):_

> ``` JavaScript
>         key,
>         hp: controllers[key].hp,
>         isTie: index > 0 && controllers[key].hp === controllers[Object.keys(controllers)[index]].hp
> ```

全ての列挙で、Object.keys(controllers) の配列を作ってしまうのは、やや重いかと思いますので、map する前に変数として確保し、それを参照するのはいかがでしょうか。

---

_[dashboard/js/socketManager.js, line 46 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/30#-KNLOd3qlRNEfextw0of:-KNLOd3qlRNEfextw0og:1914415291) ([raw file](https://github.com/comozilla/onigo-server/blob/50d8d983b26842ccc4a5a3d44f78c2db7b92f162/dashboard/js/socketManager.js#L46)):_

> ``` JavaScript
> 
> SocketManager.prototype.sendRankingState = function(rankingState) {
>   console.log(rankingState);
> ```

ここのログはみたいログ？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/30)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[rankingMaker.js, line 18 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/30#-KNLNkEj0qRLgm3CbScD:-KNLWRpQaemg8FBlfkuD:832887645) ([raw file](https://github.com/comozilla/onigo-server/blob/50d8d983b26842ccc4a5a3d44f78c2db7b92f162/rankingMaker.js#L18)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 全ての列挙で、Object.keys(controllers) の配列を作ってしまうのは、やや重いかと思いますので、map する前に変数として確保し、それを参照するのはいかがでしょうか。
> </details>
> そうします！

---

_[dashboard/js/socketManager.js, line 46 [r1]](https://reviewable.io:443/reviews/comozilla/onigo-server/30#-KNLOd3qlRNEfextw0of:-KNLWTXJ7IpD_ZN37Rr2:2110946819) ([raw file](https://github.com/comozilla/onigo-server/blob/50d8d983b26842ccc4a5a3d44f78c2db7b92f162/dashboard/js/socketManager.js#L46)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここのログはみたいログ？
> </details>
> すみません、デバッグ時の消し忘れです。消します。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/30)_

**Comment by dadaa** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[main.js, line 113 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/30#-KNLXBcEi3__9AudVi8c:-KNLXBcEi3__9AudVi8d:-425898356) ([raw file](https://github.com/comozilla/onigo-server/blob/34570d190dfa898b26d8d1fd612b08596dd301a9/main.js#L113)):_

> ``` JavaScript
>   if (state === "show") {
>     const ranking = rankingMaker.make(controllerModel.controllers);
>     Object.keys(controllerModel.controllers).forEach(key => {
> ```

ここの keys() も上記の keys() と参照が同じなので、変数でとっておきましょう

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/30)_

**Comment by shundroid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[main.js, line 113 [r2]](https://reviewable.io:443/reviews/comozilla/onigo-server/30#-KNLXBcEi3__9AudVi8c:-KNLXbT1omrE9LOVpLaf:-1635702748) ([raw file](https://github.com/comozilla/onigo-server/blob/34570d190dfa898b26d8d1fd612b08596dd301a9/main.js#L113)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここの keys() も上記の keys() と参照が同じなので、変数でとっておきましょう
> </details>
> そうします

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/30)_

**Comment by dadaa** [comment]
Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-server/30)_

**Pull request merged**
